### PR TITLE
Fix sidebar background bug

### PR DESCRIPTION
**Pull request by JamyGolden**
This commit should address the issues mentioned in https://github.com/tinted-theming/tinted-sublime-text/issues/2

Previously dark themes looked something like this (using base16-ocean here):

image

And now base16-ocean looks like this:

image

### CODE REVIEW

**Comment by sergiorussia** [comment]
looks great, what r we waiting for to merge? for some other reviewer?

**Comment by sergiorussia** [comment]
looks great, what r we waiting for to merge? for some other reviewer? :)

**Comment by JamyGolden** [comment]
I wanted to wait a little bit to see if you or anyone had any comments before merging :sweat_smile:

**Comment by sergiorussia** [comment]
:) @JamyGolden thanks for the fix, just checked - looks great

**Comment by sergiorussia** [comment]
@JamyGolden i think there are more places left to fix, i'll create another issue #4

**Pull request merged**
